      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: ''
          accept-android-sdk-licenses: false

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0"
